config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :tests
  resources :teachers
  resources :subjects
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mark.rb
class Mark < ApplicationRecord
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: [:show, :edit, :update, :destroy]

  # GET /marks
  # GET /marks.json
  def index
    @marks = Mark.all
  end

  # GET /marks/1
  # GET /marks/1.json
  def show
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks
  # POST /marks.json
  def create
    @mark = Mark.new(mark_params)

    respond_to do |format|
      if @mark.save
        format.html { redirect_to @mark, notice: 'Mark was successfully created.' }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marks/1
  # PATCH/PUT /marks/1.json
  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to @mark, notice: 'Mark was successfully updated.' }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1
  # DELETE /marks/1.json
  def destroy
    @mark.destroy
    respond_to do |format|
      format.html { redirect_to marks_url, notice: 'Mark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mark_params
      params.require(:mark).permit(:mark, :comment)
    end
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/views/marks/_form.html.erb
<%= form_for(mark) do |f| %>
  <% if mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mark.errors.count, "error") %> prohibited this mark from being saved:</h2>

      <ul>
      <% mark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mark %>
    <%= f.text_field :mark %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/marks/edit.html.erb
<h1>Editing Mark</h1>

<%= render 'form', mark: @mark %>

<%= link_to 'Show', @mark %> |
<%= link_to 'Back', marks_path %>

app/views/marks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marks</h1>

<table>
  <thead>
    <tr>
      <th>Mark</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marks.each do |mark| %>
      <tr>
        <td><%= mark.mark %></td>
        <td><%= mark.comment %></td>
        <td><%= link_to 'Show', mark %></td>
        <td><%= link_to 'Edit', edit_mark_path(mark) %></td>
        <td><%= link_to 'Destroy', mark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mark', new_mark_path %>

app/views/marks/new.html.erb
<h1>New Mark</h1>

<%= render 'form', mark: @mark %>

<%= link_to 'Back', marks_path %>

app/views/marks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mark:</strong>
  <%= @mark.mark %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @mark.comment %>
</p>

<%= link_to 'Edit', edit_mark_path(@mark) %> |
<%= link_to 'Back', marks_path %>